# Generated by Django 4.0.3 on 2022-03-07 08:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='location',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='title',
            new_name='job_title',
        ),
        migrations.AddField(
            model_name='education',
            name='level',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
