# Generated by Django 4.0.3 on 2022-03-09 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Contact',
        ),
    ]
